name: "Pull Request checks"

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: "./.github/actions/build-and-test"
        with:
          image-name: bronzedeer/k8s-jsonnet-runner
          image-tag: ${{ github.sha }}
