name: "Release"

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: "./.github/actions/build-and-test"
        id: build
        with:
          image-name: bronzedeer/k8s-jsonnet-runner
          image-tag: ${{ github.ref_name }}

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Publish container"
        run: docker push ${{ steps.build.outputs.image-name }}:${{ steps.build.outputs.image-tag }}
